/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libraryapp;

import javax.swing.JOptionPane;
import book.*;
import member.*;
import java.awt.Point;
import java.awt.Rectangle;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author fernandoenad
 */
public class Main extends javax.swing.JFrame {
    BookDAOImpl bookDAOImpl = new BookDAOImpl("books.txt");
    MemberDAOImpl memberDAOImpl = new MemberDAOImpl("members.txt");
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        loadTables();
    }

    public void loadTables(){
        loadBooks();
        loadMembers();
    }
    
    public void loadBooks(){
        DefaultTableModel model = (DefaultTableModel) booksTblBooks.getModel();
        model.setRowCount(0);
        
        for(Book b : bookDAOImpl.viewAll()){
            model.addRow(new Object[]{b.getId(), b.getIsbn(), b.getTitle(), b.getAuthor(), b.getPublisher(), b.getYearPublished(), b.getCategory(), b.getStatusRemarks()});
        }
        
    }
    
    public void loadMembers(){
        DefaultTableModel model = (DefaultTableModel) membersTblMembers.getModel();
        model.setRowCount(0);
        
        for(Member m : memberDAOImpl.viewAll()){
            model.addRow(new Object[]{m.getId(), m.getName(), m.getEmail(), m.getContactNumber(), m.getAddress(), m.getDateJoined(), m.getStatusRemarks()});
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        booksPopupMenu = new javax.swing.JPopupMenu();
        booksPopupMenuEdit = new javax.swing.JMenuItem();
        booksPopupMenuDelete = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabHome = new javax.swing.JPanel();
        tabTransactions = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionsTblTransactions = new javax.swing.JTable();
        transactionsTfSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        transactionsBtnNew = new javax.swing.JButton();
        tabBooks = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        booksTblBooks = new javax.swing.JTable();
        booksTfSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        booksBtnNew = new javax.swing.JButton();
        tabMembers = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        membersTblMembers = new javax.swing.JTable();
        membersTfSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        membersBtnNew = new javax.swing.JButton();
        tabUsers = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        usersTblUsers = new javax.swing.JTable();
        usersTfSearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        usersBtnNew = new javax.swing.JButton();

        booksPopupMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        booksPopupMenuEdit.setText("Edit");
        booksPopupMenuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksPopupMenuEditActionPerformed(evt);
            }
        });
        booksPopupMenu.add(booksPopupMenuEdit);

        booksPopupMenuDelete.setText("Delete");
        booksPopupMenuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksPopupMenuDeleteActionPerformed(evt);
            }
        });
        booksPopupMenu.add(booksPopupMenuDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");

        javax.swing.GroupLayout tabHomeLayout = new javax.swing.GroupLayout(tabHome);
        tabHome.setLayout(tabHomeLayout);
        tabHomeLayout.setHorizontalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1043, Short.MAX_VALUE)
        );
        tabHomeLayout.setVerticalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Home", tabHome);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Transactions"));

        transactionsTblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ISBN", "Title", "Author", "Publisher", "Year Published", "Category", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transactionsTblTransactions);
        if (transactionsTblTransactions.getColumnModel().getColumnCount() > 0) {
            transactionsTblTransactions.getColumnModel().getColumn(0).setResizable(false);
            transactionsTblTransactions.getColumnModel().getColumn(1).setResizable(false);
            transactionsTblTransactions.getColumnModel().getColumn(2).setResizable(false);
            transactionsTblTransactions.getColumnModel().getColumn(3).setResizable(false);
            transactionsTblTransactions.getColumnModel().getColumn(4).setResizable(false);
            transactionsTblTransactions.getColumnModel().getColumn(5).setResizable(false);
            transactionsTblTransactions.getColumnModel().getColumn(6).setResizable(false);
            transactionsTblTransactions.getColumnModel().getColumn(7).setResizable(false);
            transactionsTblTransactions.getColumnModel().getColumn(7).setHeaderValue("Status");
        }

        jLabel1.setText("Search...");

        transactionsBtnNew.setText("New Book");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transactionsTfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                        .addComponent(transactionsBtnNew)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transactionsTfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(transactionsBtnNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabTransactionsLayout = new javax.swing.GroupLayout(tabTransactions);
        tabTransactions.setLayout(tabTransactionsLayout);
        tabTransactionsLayout.setHorizontalGroup(
            tabTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTransactionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabTransactionsLayout.setVerticalGroup(
            tabTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTransactionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Transactions", tabTransactions);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Books Management"));

        booksTblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ISBN", "Title", "Author", "Publisher", "Year Published", "Category", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        booksTblBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booksTblBooksMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(booksTblBooks);
        if (booksTblBooks.getColumnModel().getColumnCount() > 0) {
            booksTblBooks.getColumnModel().getColumn(0).setResizable(false);
            booksTblBooks.getColumnModel().getColumn(1).setResizable(false);
            booksTblBooks.getColumnModel().getColumn(2).setResizable(false);
            booksTblBooks.getColumnModel().getColumn(3).setResizable(false);
            booksTblBooks.getColumnModel().getColumn(4).setResizable(false);
            booksTblBooks.getColumnModel().getColumn(5).setResizable(false);
            booksTblBooks.getColumnModel().getColumn(6).setResizable(false);
            booksTblBooks.getColumnModel().getColumn(7).setResizable(false);
            booksTblBooks.getColumnModel().getColumn(7).setHeaderValue("Status");
        }

        booksTfSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                booksTfSearchCaretUpdate(evt);
            }
        });

        jLabel4.setText("Search...");

        booksBtnNew.setText("New Book");
        booksBtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksBtnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(booksTfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                        .addComponent(booksBtnNew)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(booksTfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(booksBtnNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabBooksLayout = new javax.swing.GroupLayout(tabBooks);
        tabBooks.setLayout(tabBooksLayout);
        tabBooksLayout.setHorizontalGroup(
            tabBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabBooksLayout.setVerticalGroup(
            tabBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Books", tabBooks);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Members Management"));

        membersTblMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Contact Number", "Address", "Date Joined", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(membersTblMembers);
        if (membersTblMembers.getColumnModel().getColumnCount() > 0) {
            membersTblMembers.getColumnModel().getColumn(0).setResizable(false);
            membersTblMembers.getColumnModel().getColumn(1).setResizable(false);
            membersTblMembers.getColumnModel().getColumn(2).setResizable(false);
            membersTblMembers.getColumnModel().getColumn(3).setResizable(false);
            membersTblMembers.getColumnModel().getColumn(4).setResizable(false);
            membersTblMembers.getColumnModel().getColumn(5).setResizable(false);
            membersTblMembers.getColumnModel().getColumn(6).setResizable(false);
        }

        membersTfSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                membersTfSearchCaretUpdate(evt);
            }
        });

        jLabel5.setText("Search...");

        membersBtnNew.setText("New Member");
        membersBtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membersBtnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(membersTfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                        .addComponent(membersBtnNew)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(membersTfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(membersBtnNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabMembersLayout = new javax.swing.GroupLayout(tabMembers);
        tabMembers.setLayout(tabMembersLayout);
        tabMembersLayout.setHorizontalGroup(
            tabMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMembersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabMembersLayout.setVerticalGroup(
            tabMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMembersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Members", tabMembers);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Users Management"));

        usersTblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ISBN", "Title", "Author", "Publisher", "Year Published", "Category", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(usersTblUsers);
        if (usersTblUsers.getColumnModel().getColumnCount() > 0) {
            usersTblUsers.getColumnModel().getColumn(0).setResizable(false);
            usersTblUsers.getColumnModel().getColumn(1).setResizable(false);
            usersTblUsers.getColumnModel().getColumn(2).setResizable(false);
            usersTblUsers.getColumnModel().getColumn(3).setResizable(false);
            usersTblUsers.getColumnModel().getColumn(4).setResizable(false);
            usersTblUsers.getColumnModel().getColumn(5).setResizable(false);
            usersTblUsers.getColumnModel().getColumn(6).setResizable(false);
            usersTblUsers.getColumnModel().getColumn(7).setResizable(false);
            usersTblUsers.getColumnModel().getColumn(7).setHeaderValue("Status");
        }

        jLabel6.setText("Search...");

        usersBtnNew.setText("New Book");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usersTfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                        .addComponent(usersBtnNew)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usersTfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(usersBtnNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabUsersLayout = new javax.swing.GroupLayout(tabUsers);
        tabUsers.setLayout(tabUsersLayout);
        tabUsersLayout.setHorizontalGroup(
            tabUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabUsersLayout.setVerticalGroup(
            tabUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Users", tabUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void booksBtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksBtnNewActionPerformed
        // TODO add your handling code here:
        BookNew bookNew = new BookNew(this, true);
        bookNew.setVisible(true);
        
        if(!bookNew.getConfirm()){
            return;
        }
        
        try{
            Book b = bookNew.getBook();
            int id = bookDAOImpl.getLastRecord() == null ? 1 : bookDAOImpl.getLastRecord().getId() + 1;
            b.setId(id);
            
            bookDAOImpl.add(b);
            loadBooks();
            JOptionPane.showMessageDialog(null, "Record was saved!", "System Information!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage() + "!", "System Error!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_booksBtnNewActionPerformed

    private void booksTfSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_booksTfSearchCaretUpdate
        // TODO add your handling code here:
        String str = booksTfSearch.getText();
        DefaultTableModel model = (DefaultTableModel) booksTblBooks.getModel();
        model.setRowCount(0);
        
        for(Book b : bookDAOImpl.search(str)){
            model.addRow(new Object[]{b.getId(), b.getIsbn(), b.getTitle(), b.getAuthor(), b.getPublisher(), b.getYearPublished(), b.getCategory(), b.getStatusRemarks()});
        }
    }//GEN-LAST:event_booksTfSearchCaretUpdate

    private void booksTblBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksTblBooksMouseClicked
        // TODO add your handling code here:
        Point p = booksTblBooks.getMousePosition();

        if (p != null) {
            booksPopupMenu.show(booksTblBooks, p.x, p.y);
        } else {
            int row = booksTblBooks.getSelectedRow();
            if(row != -1) {
                Rectangle rect = booksTblBooks.getCellRect(row, 0, true);
                booksPopupMenu.show(booksTblBooks, rect.x, rect.y);
            }
        }
    }//GEN-LAST:event_booksTblBooksMouseClicked

    private void booksPopupMenuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksPopupMenuDeleteActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Are you sure?", "System Confirmation!", JOptionPane.OK_CANCEL_OPTION);
        
        if(option != JOptionPane.OK_OPTION){
            return;
        }

        try{   
            DefaultTableModel model = (DefaultTableModel) booksTblBooks.getModel();
            int row = booksTblBooks.getSelectedRow();
            int col = 0;
            int id = Integer.parseInt(model.getValueAt(row, col).toString());
            
            bookDAOImpl.deleteById(id);
            loadBooks();
            JOptionPane.showMessageDialog(null, "Record was deleted!", "System Information!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage() + "!", "System Error!", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_booksPopupMenuDeleteActionPerformed

    private void booksPopupMenuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksPopupMenuEditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) booksTblBooks.getModel();
        int row = booksTblBooks.getSelectedRow();
        int col = 0;
        int id = Integer.parseInt(model.getValueAt(row, col).toString());
        
        Book bo = bookDAOImpl.viewById(id);
        
        BookUpdate bookUpdate = new BookUpdate(this, true, bo);
        bookUpdate.setVisible(true);
        
        if(!bookUpdate.getConfirm()){
            return;
        }
        
        try{
            Book bu = bookUpdate.getBook();
            
            bookDAOImpl.updateById(id, bu);
            loadBooks();
            JOptionPane.showMessageDialog(null, "Record was updated!", "System Information!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage() + "!", "System Error!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_booksPopupMenuEditActionPerformed

    private void membersBtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membersBtnNewActionPerformed
        // TODO add your handling code here:
        MemberNew memberNew = new MemberNew(this, true);
        memberNew.setVisible(true);
        
        if(!memberNew.getConfirm()){
            return;
        }
        
        try{
            Member m = memberNew.getBook();
            int id = memberDAOImpl.getLastRecord() == null ? 1 : memberDAOImpl.getLastRecord().getId() + 1;
            m.setId(id);
            
            memberDAOImpl.add(m);
            loadMembers();
            JOptionPane.showMessageDialog(null, "Record was saved!", "System Information!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage() + "!", "System Error!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_membersBtnNewActionPerformed

    private void membersTfSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_membersTfSearchCaretUpdate
        // TODO add your handling code here:
        String str = membersTfSearch.getText();
        DefaultTableModel model = (DefaultTableModel) membersTblMembers.getModel();
        model.setRowCount(0);
        
        for(Member m : memberDAOImpl.search(str)){
            model.addRow(new Object[]{m.getId(), m.getName(), m.getEmail(), m.getContactNumber(), m.getAddress(), m.getDateJoined(), m.getStatusRemarks()});
        }
    }//GEN-LAST:event_membersTfSearchCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton booksBtnNew;
    private javax.swing.JPopupMenu booksPopupMenu;
    private javax.swing.JMenuItem booksPopupMenuDelete;
    private javax.swing.JMenuItem booksPopupMenuEdit;
    private javax.swing.JTable booksTblBooks;
    private javax.swing.JTextField booksTfSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton membersBtnNew;
    private javax.swing.JTable membersTblMembers;
    private javax.swing.JTextField membersTfSearch;
    private javax.swing.JPanel tabBooks;
    private javax.swing.JPanel tabHome;
    private javax.swing.JPanel tabMembers;
    private javax.swing.JPanel tabTransactions;
    private javax.swing.JPanel tabUsers;
    private javax.swing.JButton transactionsBtnNew;
    private javax.swing.JTable transactionsTblTransactions;
    private javax.swing.JTextField transactionsTfSearch;
    private javax.swing.JButton usersBtnNew;
    private javax.swing.JTable usersTblUsers;
    private javax.swing.JTextField usersTfSearch;
    // End of variables declaration//GEN-END:variables
}
