/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package libraryapp;

import java.util.*;
import member.*;
import book.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import transaction.*;
import user.User;

/**
 *
 * @author fernandoenad
 */
public class TransactionUpdate extends javax.swing.JDialog {
    private List<Member> members = new ArrayList<Member>();
    private List<Book> books = new ArrayList<Book>();
    private boolean confirmed = false;
    private Transaction transaction = null;
    
    /**
     * Creates new form TransactionNew
     */
    public TransactionUpdate(java.awt.Frame parent, boolean modal, List<Member> members, List<Book> books, Transaction transaction) {
        super(parent, modal);
        initComponents();
        this.members = members;
        this.books = books;
        this.transaction = transaction;
        initializeCB();
        populateForm();
    }

    public void initializeCB(){        
        Book book_ph = new Book(-1, -1, "---Please select---", "", "", -1, "", 1);
        DefaultComboBoxModel<Book> book_model = new DefaultComboBoxModel<>();
        book_model.addElement(book_ph);
        
        for (Book b : this.books) {
            book_model.addElement(b);
        }
        
        cbBook_id.setModel(book_model);
    }
    
    public Transaction getTransaction(){
        return this.transaction;
    }
    
    public boolean getConfirm(){
        return this.confirmed;
    } 
    
    public void populateForm(){
        tfId.setText(String.format("%s",this.transaction.getId()));
        
        for(int i=0; i<this.members.size(); i++){
            if(this.transaction.getMember_id() == this.members.get(i).getId()){
                tfBorrower.setText(String.format("%s", this.members.get(i).getName()));
                break;
            }
        }
        
        for (int i = 0; i < cbBook_id.getItemCount(); i++) {            
            Book bi = (Book) cbBook_id.getItemAt(i);
            System.out.println(bi.getId());
            System.out.println(this.transaction.getBook_id());
            if (bi.getId() == this.transaction.getBook_id()) {
                cbBook_id.setSelectedIndex(i);
                break;
            }
        }
        
        tfDateBorrowed.setText(String.format("%s",this.transaction.getDateBorrowed()));
        tfDateDue.setText(String.format("%s",this.transaction.getDateDue()));

        if(this.transaction.getStatus() == 1){
            rbtnReturned.setSelected(true);
        } else {
            rbtnLoaned.setSelected(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngStatus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfDateBorrowed = new javax.swing.JTextField();
        tfDateDue = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        cbBook_id = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbtnLoaned = new javax.swing.JRadioButton();
        rbtnReturned = new javax.swing.JRadioButton();
        tfBorrower = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Library Management System - New Transaction");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fill out transaction details here..."));

        jLabel1.setText("Borrower:");

        jLabel2.setText("Book:");

        jLabel3.setText("Date Borrowed:");

        jLabel4.setText("Date Due:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel5.setText("ID:");

        tfId.setEditable(false);

        jLabel6.setText("Status:");

        rbtngStatus.add(rbtnLoaned);
        rbtnLoaned.setText("Loaned");

        rbtngStatus.add(rbtnReturned);
        rbtnReturned.setText("Returned");

        tfBorrower.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnSave)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnReset)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClose))
                        .addComponent(tfDateBorrowed, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addComponent(tfDateDue, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addComponent(cbBook_id, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfId)
                        .addComponent(tfBorrower))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnLoaned)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnReturned)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbBook_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDateBorrowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDateDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbtnLoaned)
                    .addComponent(rbtnReturned))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnReset)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.confirmed = false;
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        populateForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Are you sure?", "System Confirmation!", JOptionPane.OK_CANCEL_OPTION);
        
        if(option != JOptionPane.OK_OPTION){
            return;
        }
        
        InputValidator inputValidator = new InputValidator();
        String dateBorrowed = tfDateBorrowed.getText();
        String dateDue = tfDateDue.getText();
        
        String errorMsg = "";
        
        if(!inputValidator.validateDate(dateBorrowed)){
            errorMsg += "- Date Borrowed should follow yyyy-mm-dd format.\n";
        }  
        
        if(!inputValidator.validateDate(dateDue)){
            errorMsg += "- Date Due should follow yyyy-mm-dd format.\n";
        }
       
        int book_id = -1;
        Book bs = (Book) cbBook_id.getSelectedItem();
        
        if (bs != null) {
            book_id = bs.getId(); 
        }
        
        if(book_id < 0){
            errorMsg += "- Book Title must be selected.\n";
        } 
        
        int status = 0;
        
        if(rbtnReturned.isSelected()){
            status = 1;
        }

        if (errorMsg.length() > 0) {
            JOptionPane.showMessageDialog(this, "Please correct the following errors:\n" + errorMsg.toString(), "Validation Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        try {
            this.transaction = new Transaction(this.transaction.getId(), this.transaction.getMember_id(), book_id, dateBorrowed, dateDue, status);
            this.confirmed = true;
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fatal Error: Numeric data is too large for the system.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TransactionUpdate dialog = new TransactionUpdate(new javax.swing.JFrame(), true, null, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Book> cbBook_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtnLoaned;
    private javax.swing.JRadioButton rbtnReturned;
    private javax.swing.ButtonGroup rbtngStatus;
    private javax.swing.JTextField tfBorrower;
    private javax.swing.JTextField tfDateBorrowed;
    private javax.swing.JTextField tfDateDue;
    private javax.swing.JTextField tfId;
    // End of variables declaration//GEN-END:variables
}
